model:
  num_codebooks: 4
  stereo: false

  codebook_size: 1024
  pad_token_id: 1024
  
  hidden_size: 1024
  decoder_depth: 12
  decoder_heads: 16
  rotary_emb: false

  memory_dim: 1024
  max_seq_length: 1920
  max_prompt_length: 1024

  text_encoder: 'google-t5/t5-large'
  compile: false

data:
  dataset_id: 'WaveGenAI/dataset'
  audio_column: 'codes'
  text_column: 'prompt'

train:
  max_epochs: 13
  accumulate_grad_batches: 32
  batch_size: 1
  gradient_clip_val: 1
  warmup_steps: 1
  lr_max: 0.00095
  lr_min: 0.000001  
  test_model: true
  train_num_workers: 15
  val_num_workers: 4
  log_every_n_steps: 10_000 
  noise_mean: 0.1
  noise_std: 0.5
  duration_audio_test: 10

  shuffle_data: true
