model:
  num_codebooks: 6
  stereo: true

  codebook_size: 1024
  pad_token_id: 1024
  start_token_id: 1025
  end_token_id: 1026

  hidden_size: 1024
  decoder_depth: 12
  decoder_heads: 16
  rotary_emb: true

  memory_dim: 1024
  max_seq_length: 1500
  max_prompt_length: 1024

  text_encoder: 'google-t5/t5-large'
  compile: false

data:
  dataset_id: '/media/works/data/data/'
  audio_column: 'codes.npy'
  text_column: 'prompt.txt'
  chunk_id: 'chunk_id.txt'
  num_chunks: 'total_chunks.txt'
  audio_embed_column: 'embd.npy'
  shuffle_data: false
  train_size: 200_000
  
train:
  max_epochs: 13 
  accumulate_grad_batches: 1
  batch_size: 1
  gradient_clip_val: 1
  warmup_steps: 1
  lr_max: 0.00095
  lr_min: 0.000001  
  test_model: true
  train_num_workers: 15
  val_num_workers: 4
  log_every_n_steps: 5_000 
  duration_audio_test: 10
  noise_mean: 0.1
  noise_std: 0.5

  debug: true
